image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 9
  GH_TOKEN:
    secure: JQTogieeX60CDa5l+4NGvmE3do+t8iDPrrppjHYfGbx2vlGMvNUtPbJvnsqZ07tF

cache:
  - '%LOCALAPPDATA%/Yarn'
  - node_modules -> package.json
  - app/node_modules -> app/package.json
  - flow-typed
  - '%USERPROFILE%\.electron'

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - yarn

test_script:
  - yarn package-ci
  - yarn lint
  # - yarn flow
  - yarn test
  - yarn build-e2e
  - yarn test-e2e
